[package]
name = "blazesym"
description = "BlazeSym is a library that symbolizes addresses where symbol names, source file names, and line numbers can be acquired."
version = "0.1.0"
authors = ["Kui-Feng <thinker.li@gmail.com>"]
license-file = "LICENSE"
repository = "https://github.com/libbpf/blazesym"
edition = "2021"
exclude = ["data/dwarf-example", "data/kallsyms.xz"]
autobenches = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "blazesym"
crate-type = ["cdylib", "rlib", "staticlib"]

[[bench]]
name = "main"
harness = false
required-features = ["generate-bench-files"]

[dependencies]
crossbeam-channel = "0.5"
libc = "0.2.137"
lru = "0.10"
memmap = "0.7"
nix = "0.24"
regex = "1.6"

[dev-dependencies]
blazesym = {path = ".", features = ["generate-test-files"]}
criterion = "0.4"

[build-dependencies]
anyhow = "1.0.68"
cbindgen = {version = "0.24", optional = true}
xz2 = {version = "0.1.7", optional = true}

[features]
# Enable this feature to re-generate the library's C header file. An
# up-to-date version of this header should already be available in the
# include/ directory, so this feature is only necessary when APIs are
# changed.
generate-c-header = ["cbindgen"]
# Enable this feature to opt in to the generation of test files. Having test
# files created is necessary for running tests.
generate-test-files = ["xz2"]
# Enable this feature to opt in to the generation of benchmark files.
# This feature is required for some of the benchmarks. Note that git-lfs
# needs to be installed in this case.
generate-bench-files = ["xz2"]
# Disable generation of test files. This feature takes preference over
# `generate-test-files`.
dont-generate-test-files = []
# Enable code paths requiring a nightly toolchain. This feature is only meant to
# be used for testing and benchmarking purposes, not for the core library, which
# is expected to work on stable.
nightly = []
