[package]
name = "blazecli"
version = "0.0.0"
edition = "2021"
default-run = "blazecli"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "shell-complete"
path = "utils/shell-complete.rs"
required-features = ["clap_complete"]

[build-dependencies]
anyhow = "1.0.68"
grev = "0.1.3"

[dependencies]
anyhow = "1.0.68"
blazesym = {path = "../../"}
clap = {version = "4.1.7", features = ["derive"]}
clap_complete = {version = "4.1.1", optional = true}
tracing = {version = "0.1", default-features = false, features = ["std"]}
tracing-subscriber = {version = "0.3", default-features = false, features = ["ansi", "env-filter", "fmt"]}
