name: Test

on:
  push:
  pull_request:
  workflow_call:

env:
  CARGO_TERM_COLOR: always
  # Enable backtraces for panics but not for "regular" errors.
  RUST_BACKTRACE: 1
  RUST_LIB_BACKTRACE: 0
  RUSTFLAGS: '-D warnings'

jobs:
  build-test-artifacts:
    # Only run tests on other operating systems on the final push. They
    # are very unlikely to break at runtime (we build them anyway), but
    # take quite a bit longer than Linux based ones.
    name: Build test artifacts
    runs-on: ubuntu-24.04
    env:
      LLVM_GSYMUTIL: /usr/bin/llvm-gsymutil-18
    steps:
    - name: Install development dependencies
      run: |
        sudo apt-get update
        sudo apt-get install --yes --no-install-recommends gcc-multilib libelf-dev zlib1g-dev
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable
    - run: cargo check --package=blazesym-dev --features=generate-unit-test-files
    - uses: actions/upload-artifact@v4
      with:
        name: test-stable-addrs
        if-no-files-found: error
        path: |
          data/libtest-so*
          data/test-no-debug.bin
          data/test-rs.bin
          data/test-stable-addrs*
  test-partly-supported:
    name: Test on ${{ matrix.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        runs-on: [macos-latest, windows-latest]
    runs-on: ${{ matrix.runs-on }}
    needs: [build-test-artifacts]
    steps:
    - uses: actions/checkout@v4
    - uses: actions/download-artifact@v4
      with:
        name: test-stable-addrs
        path: data/
    - uses: dtolnay/rust-toolchain@stable
    - run: cargo test --tests --workspace --release --features=blazesym-dev/dont-generate-unit-test-files --features=blazesym-c/dont-check-doc-snippets -- ':other_os:'
